AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function to poll SQS and process messages in SQS and write output to S3 bucket.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15

Resources:
  TestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: lambda.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          LOCALSTACK : True
      Policies:
        - SQSPollerPolicy:
            QueueName: my-queue
        - S3WritePolicy:
            BucketName: macy-localstack-demo

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TestFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt TestFunction.Arn


