version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localstack-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xo9jklp6zi1f"
s3_prefix = "localstack-1"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
